---
title: "Curriculum Vitae"

format:
  html:
    toc: true
  pdf:
    author: Quandong Pan
    pdf-engine: weasyprint
css: cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
**(He/Him)**

**quandong.pan\@email.uni-freiburg.de**

**Website**: <https://quandongpan.github.io/>
:::

<br>

## “Embrace Complexity”

-   *"There is no flood in a single raindrop, no financial crash in a single dollar, and no love in a single carbon atom. Yet, when combined under certain conditions, these simple elements create phenomena far greater and more complex than their individual parts." --- The Science of Complexity*

<br>

## Research Interests:

-   I am driven to understand the **fundamental principles underlying biological processes** like regeneration, pattern formation and multicellularity etc, through employing **experimental and computational techniques**, including scRNA‐seq, multi-omics integration, modeling the intricate dynamics of gene regulatory networks and the epigenetic landscape, ultimately seeking to control these systems through the combined power of **systems biology and bioengineering**.

<br>

## Fields of Interest in General:

-   Systems Biology

-   Synthetic Biology & Biotechnology

-   Metabolic & Genetic Engineering

-   Directed Evolution and Optimization of Microorganisms

-   Evolutionary Developmental Biology

-   Regeneration and Morphogenesis

-   Organoids, Biofilms and Multicellularity

-   Self-Organization and Emergence

-   Multiscale Analysis of Cellular Systems

-   Network Science and Complex Systems Modeling

-   Attractor Landscape Analysis of GRNs

<br>

## Education

**Bachelor of Science -- Major: Life Sciences**

***University of Freiburg***

*Oct 2022 --- Present*

<https://uni-freiburg.de/ucf/las/curriculum/#life-sciences>

<br>

## Relevant Coursework

-   Cell Biology

-   Basic Chemistry and Biochemistry

-   Genetics and Epigenetics

-   Data Science with R

-   Computational Genomics

-   Human Cognition and Artificial Intelligence

-   Engineering with Living Materials

<br>

## Research Experience {style="page-break-before: no"}

### **Research Internship—Baumeister Lab**

#### Bioinformatics & Molecular Genetics

##### University of Freiburg, Faculty of Biology

<https://celegans.biologie.uni-freiburg.de/?page_id=391>

\[ Oct 2025-Present \]

-   The lab studies stress response and signaling pathways in *C. elegans,* which includes:

    -   Cross talk between insulin and TOR signaling in tumorigenesis and stress response

    -   Signaling function of Parkinson’s Disease genes

    -   Mitochondrial stress response

-   I acquired skills of transgenic *C. elegans* construction, RNAi mediated gene control, fluorescence microscopy, phenotypical and survival analysis etc.

<br>

{{< pagebreak >}}

### Research Internship—The Bonasio Lab

#### Molecular Mechanisms of Epigenetic Memory

##### University Hospital Freiburg

<https://www.bonasiolab.org/#top>

\[ 03/04/2024 – 30/04/2024 \]

The lab focuses on the molecular mechanisms of epigenetic memory, particularly interested in elucidating the epigenetic mechanisms of caste transition and reversion in *Harpegnathos saltator* ant:

-   My role was primarily focused on conducting behavioral analysis of the *Harpegnathos saltator* ant colony during its transition phase induced by colony separation.

<br>

## Conferences

-   Horizons in Molecular Biology Symposium 2025 in Göttingen

    -   \[ 08/09/2025 – 11/09/2025 \] Max Planck Institute for Multidisciplinary Sciences
    -   Biochemistry and Molecular Biology, Cell Biology
    -   Genome Biology, Developmental Biology
    -   Structural Biology, Molecular Neuroscience, Computational Biology
    -   Link: <https://www.mpinat.mpg.de/horizons>

-   Life Sciences Annual Meeting 2024 in Switzerland

    -   \[ 13/02/2024 – 15/02/2024 \] University of Lausanne
    -   Bioinformatics, Biophysics, Cardiovascular Biology & Physiology
    -   Experimental Pharmacology, Ion Channels and Membrane Transporters Microscopy
    -   Molecular and Cellular Biosciences, Proteomics and Systems Biology
    -   Link: <https://annual-meeting.ls2.ch/2024/program>

-   SY-Stem Cell Conference 2024 in Vienna

    -   \[ 13/03/2024 – 15/03/2024 \] Vienna BioCenter, Austria
    -   Early Embryogenesis
    -   Neural lineage specification
    -   Nervous Systems Development
    -   Brain Disease, Regeneration and Novel Technologies
    -   Link: <https://www.oeaw.ac.at/imba/seminars-events/past-events/sy-stem-2024>

-   Interdisciplinary College 2024 of Complex Systems in Germany:

    -   \[ 01/03/2024 – 08/03/2024 \]
    -   Computational Neuroscience, Machine Learning, Game theory
    -   Theoretical Biology and Complex Dynamical Systems Simulation
    -   Link: <https://interdisciplinary-college.org/program/>

<br>

{{< pagebreak >}}

## Skills

-   Programming Language：

    -   R Language
    -   MATLAB and Python

-   Software and Platform: R Studio, MATLAB, Github, NetLogo

-   Basic Skills in Molecular and Experimental Biology

<br>

## Language Proficiency

-   Chinese (Native)

-   English

    -   IELTs (Scale of 9)

        -   (Overall 7.0, Listening 7.0, Reading 7.5, Speaking, 7.5, Writing 6.5)

    -   PTE Academic (Scale of 90)

        -   (Overall 86, Listening 80, Reading 90, Speaking, 72, Writing 90)

-   German B2
